Repository anoma/anoma, pull requests merged in 2021-11, with the labels that each got.

#642 update docs prototypes pages
  docs/src/explore/prototypes/base-ledger.md
  docs/src/explore/prototypes/gossip-layer.md
Labels: documentation

#653 Tx data contains tx type
  apps/src/lib/node/ledger/shell/finalize_block.rs
  apps/src/lib/node/ledger/shell/prepare_proposal.rs
  apps/src/lib/node/ledger/shell/process_proposal.rs
  shared/src/types/transaction/decrypted.rs
  shared/src/types/transaction/mod.rs
  shared/src/types/transaction/wrapper.rs
Labels: enhancement, ledger

#609 replace the `anoma` process with the sub-command
  Cargo.lock
  apps/Cargo.toml
  apps/src/bin/anoma/cli.rs
Labels: merged to next, ok for maint

#613 Minor docs and scripts improvements
  scripts/install/get_tendermint.sh
Labels: ok for maint

#614 switch to tower-abci branch with patched rx selection
  Cargo.lock
  apps/Cargo.toml
  apps/src/lib/node/ledger/mod.rs
  apps/src/lib/node/ledger/shell/process_proposal.rs
  shared/src/types/key/ed25519.rs
  wasm/checksums.json
Labels: ok for maint

#615 add conditional compilation on rlimit for unix only
  apps/src/lib/node/ledger/storage/rocksdb.rs
Labels: ok for maint

#627 [apps/node/ledger/storage] write block from references
  apps/src/lib/node/ledger/storage/rocksdb.rs
  shared/src/ledger/storage/mockdb.rs
  shared/src/ledger/storage/mod.rs
Labels: ok for maint

#616 init-network create archive for anoma-network-config release
  Cargo.lock
  apps/Cargo.toml
  apps/src/lib/cli.rs
  apps/src/lib/client/utils.rs
  apps/src/lib/config/global.rs
  apps/src/lib/config/mod.rs
  tests/src/e2e/setup.rs
Labels: ok for maint

#617 init-network set open P2P if not localhost
  apps/src/lib/client/utils.rs
Labels: ok for maint

#644 add wasm checksums in init-network cmd
  apps/src/lib/cli.rs
  apps/src/lib/client/utils.rs
  apps/src/lib/wasm_loader/mod.rs
  tests/src/e2e/setup.rs
Labels: ok for maint
