Repository anoma/anoma, pull requests merged in 2022-02, with the labels that each got.

#848 IBC FungibleTransferToken follow-up
  .changelog/unreleased/improvements/848-ibc-fungible-token-transfer-follow-up.md
  shared/src/ledger/ibc/vp/token.rs
  shared/src/ledger/native_vp.rs
  shared/src/ledger/storage/write_log.rs
  shared/src/ledger/vp_env.rs
  shared/src/vm/host_env.rs
  shared/src/vm/wasm/host_env.rs
  tests/src/vm_host_env/ibc.rs
  tests/src/vm_host_env/tx.rs
  vm_env/src/imports.rs
  vm_env/src/token.rs
  wasm/checksums.json
Labels: merged to next

#862 move network config WASM dirs inside chain dir
  .changelog/unreleased/improvements/838-wasm-dir-inside-chain-dir.md
  Cargo.lock
  apps/src/bin/anoma-node/cli.rs
  apps/src/lib/cli.rs
  apps/src/lib/cli/context.rs
  apps/src/lib/client/utils.rs
  apps/src/lib/config/mod.rs
  apps/src/lib/wasm_loader/mod.rs
  tests/Cargo.toml
  tests/src/e2e/setup.rs
Labels: merged to next, ok for maint

#870 deps: downgrade wasmer to 1.0.2
  .changelog/unreleased/bug-fixes/870-downgrade-wasmer-1.0.2.md
  Cargo.lock
  shared/Cargo.toml
  shared/src/vm/wasm/compilation_cache/common.rs
  shared/src/vm/wasm/memory.rs
  shared/src/vm/wasm/run.rs
  wasm/tx_template/Cargo.lock
  wasm/vp_template/Cargo.lock
  wasm/wasm_source/Cargo.lock
  wasm_for_tests/wasm_source/Cargo.lock
Labels: ok for maint

#885 Handle connection errors in tower-abci
  .changelog/unreleased/improvements/716-tower-error-handling.md
  apps/src/lib/node/ledger/mod.rs
Labels: ok for maint
