Repository anoma/anoma, pull requests merged in 2025-06, with the labels that each got.

#1910 Make Blocks Scryable
  apps/anoma_node/lib/examples/e_transaction.ex
  apps/anoma_node/lib/node/replay/start_state.ex
  apps/anoma_node/lib/node/transaction/mempool/mempool.ex
  apps/anoma_node/lib/node/transaction/storage/storage.ex
Labels: storage

#2058 Add a `wrap` flag to the mempool to wrap transactions in a transaction candidate before submitting
  apps/anoma_client/lib/client/node/grpc_proxy.ex
  apps/anoma_client/lib/client/node/rpc.ex
  apps/anoma_client/lib/client/web/controllers/mempool/mempool.ex
  apps/anoma_client/lib/client/web/controllers/mempool/spec.ex
  apps/anoma_node/lib/node/transport/grpc/endpoint/mempool.ex
  apps/anoma_protobuf/priv/protobuf/mempool.proto
Labels: improvement

#2064 Accept integers in Cairo workflow
  apps/anoma_lib/lib/anoma/cairo_resource/workflow.ex
Labels: bug

#2065 Fix bug where Cue fails
  apps/anoma_lib/lib/nock/jets.ex
Labels: bug

#2087 Fix typo of Compling to Compiling
  apps/compile_protoc/lib/mix/tasks/compile/protoc.ex
Labels: refactoring
